// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgCnRlPQpJFjvvDi9S30FeWsabyw3H7C0',
    appId: '1:111035250921:web:66f2046395e79c46191878',
    messagingSenderId: '111035250921',
    projectId: 'respiratory-diseases-be002',
    authDomain: 'respiratory-diseases-be002.firebaseapp.com',
    storageBucket: 'respiratory-diseases-be002.firebasestorage.app',
    measurementId: 'G-QDPNPJYD63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeW-327EaqQ7en8llLW6z8X8eB5HKsJ6A',
    appId: '1:111035250921:android:4b75c986f20efb93191878',
    messagingSenderId: '111035250921',
    projectId: 'respiratory-diseases-be002',
    storageBucket: 'respiratory-diseases-be002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs19dRZcQsVaGm9ABwwZhrbg-BEG8a90E',
    appId: '1:111035250921:ios:5d089cf597de71c4191878',
    messagingSenderId: '111035250921',
    projectId: 'respiratory-diseases-be002',
    storageBucket: 'respiratory-diseases-be002.firebasestorage.app',
    iosBundleId: 'com.example.respiratoryDiseases',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgCnRlPQpJFjvvDi9S30FeWsabyw3H7C0',
    appId: '1:111035250921:web:1d65a43a05c5e808191878',
    messagingSenderId: '111035250921',
    projectId: 'respiratory-diseases-be002',
    authDomain: 'respiratory-diseases-be002.firebaseapp.com',
    storageBucket: 'respiratory-diseases-be002.firebasestorage.app',
    measurementId: 'G-XFW6N6V61X',
  );
}
